# Generated by Django 5.0.7 on 2024-08-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phLevel', models.FloatField()),
                ('pollutionLevel', models.CharField(max_length=50)),
                ('isSafe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('humidity', models.FloatField()),
                ('forecast', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='beach',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='beach',
            name='longitude',
        ),
        migrations.AddField(
            model_name='beach',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='beach',
            name='location',
            field=models.CharField(default='camps bay', max_length=255),
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('reportType', models.CharField(max_length=100)),
                ('problemType', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('additionlInfo', models.TextField()),
                ('urgency', models.TextField()),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beach')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='beach',
            name='waterQuality',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.waterquality'),
        ),
        migrations.AddField(
            model_name='beach',
            name='weather',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.weather'),
        ),
    ]
